id: PD57C5056
initial_creation_type: ocr
source_metadata:
  volumes:
    b8f22b0dc6354eb5b3eeb9fc8d2d9ff7:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: དགྱེས་པ་རྡོ་རྗེའི་སྒྲུབ་ཐབས་རིན་པོ་ཆེའི་སྒྲོན་མ།
      total_pages: 2069
      volume_number: 5
